### ISSUE TITLE
Can't find proof of the yeti

### ISSUE THREAD

**Issue by nbargnesi** [OpenBEL/openbel-server#53]
I didn't expect to find it but I expected you to at least try. :wink: 

```
> GET /api/evidence/proof-of-the-yeti HTTP/1.1
> User-Agent: curl/7.40.0
> Host: next.belframework.org
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Server: nginx/1.4.6 (Ubuntu)
< Date: Fri, 27 Feb 2015 22:51:23 GMT
< Content-Type: text/plain
< Content-Length: 8164
< Connection: keep-alive
< Keep-Alive: timeout=20
< Vary: Accept-Encoding
< 
BSON::InvalidObjectId: illegal ObjectId format: proof-of-the-yeti
	/var/lib/gems/2.0.0/gems/bson-1.12.0.rc2/lib/bson/types/object_id.rb:21:in `from_string'
	/var/lib/gems/2.0.0/gems/bson-1.12.0.rc2/lib/bson/types/object_id.rb:21:in `ObjectId'
	/home/ubuntu/projects/openbel-server/lib/evidence/mongo.rb:56:in `to_id'
	/home/ubuntu/projects/openbel-server/lib/evidence/mongo.rb:27:in `find_evidence_by_id'
	/home/ubuntu/projects/openbel-server/app/routes/evidence.rb:108:in `block in <class:Evidence>'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/var/lib/gems/2.0.0/gems/rack-1.6.0/lib/rack/logger.rb:15:in `call'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
	/var/lib/gems/2.0.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
	/var/lib/gems/2.0.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:945:in `forward'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1019:in `route_missing'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:980:in `route!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/var/lib/gems/2.0.0/gems/rack-1.6.0/lib/rack/logger.rb:15:in `call'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
	/var/lib/gems/2.0.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
	/var/lib/gems/2.0.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:945:in `forward'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1019:in `route_missing'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:980:in `route!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:976:in `route!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
	/var/lib/gems/2.0.0/gems/rack-1.6.0/lib/rack/logger.rb:15:in `call'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
	/var/lib/gems/2.0.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
	/var/lib/gems/2.0.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/var/lib/gems/2.0.0/gems/rack-cors-0.3.1/lib/rack/cors.rb:72:in `call'
	/var/lib/gems/2.0.0/gems/rack-1.6.0/lib/rack/deflater.rb:35:in `call'
	/var/lib/gems/2.0.0/gems/rack-1.6.0/lib/rack/logger.rb:15:in `call'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:210:in `call'
	/var/lib/gems/2.0.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
	/var/lib/gems/2.0.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
	/var/lib/gems/2.0.0/gems/puma-2.11.0/lib/puma/rack_patch.rb:13:in `call'
	/var/lib/gems/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:217:in `call'
	/var/lib/gems/2.0.0/gems/puma-2.11.0/lib/puma/configuration.rb:82:in `call'
	/var/lib/gems/2.0.0/gems/puma-2.11.0/lib/puma/server.rb:507:in `handle_request'
	/var/lib/gems/2.0.0/gems/puma-2.11.0/lib/puma/server.rb:375:in `process_client'
	/var/lib/gems/2.0.0/gems/puma-2.11.0/lib/puma/server.rb:262:in `block in run'
	/var/lib/gems/2.0.0/gems/puma-2.11.0/lib/puma/thread_pool.rb:104:in `call'
* Connection #0 to host next.belframework.org left intact
	/var/lib/gems/2.0.0/gems/puma-2.11.0/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```

**Comment by nbargnesi** [comment]
Thanks 😊!
